allowBuilds:
  '@swc/core': true
  esbuild: true

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  esbuild@>=0.27.3 <0.28.1: '>=0.28.1'
  piscina@<=4.9.2: '>=4.9.3'
  undici@>=7.0.0 <7.28.0: '>=7.28.0'
  undici@>=7.23.0 <7.28.0: '>=7.28.0'
